version: '3.7'

services:
  web:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ..:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ../tubestack_backend/.env
    environment:
      - PROD=0
    depends_on:
      - db
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../tubestack_backend/.env

  rabbitmq:
    image: rabbitmq:3
    env_file: ../tubestack_backend/.env
    ports:
      - "5672:5672"

  celery:
    build: ../tubestack_backend
    env_file: ../tubestack_backend/.env
    command: bash -c "celery -A tubestack_backend worker -l info"
    depends_on:
      - db
      - rabbitmq

  celery-beat:
    build: ../tubestack_backend
    env_file: ../tubestack_backend/.env
    command: bash -c "celery -A tubestack_backend beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - db
      - rabbitmq

volumes:
  postgres_data: