# Generated by Django 3.0.7 on 2020-10-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_module', '0001_initial'),
        ('users_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_list', to='youtube_module.Keyword'),
        ),
    ]
