# Generated by Django 3.0.7 on 2020-10-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('video_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('channel_name', models.CharField(max_length=300)),
                ('published_at', models.DateTimeField()),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword', to='youtube_module.Keyword')),
            ],
            options={
                'verbose_name_plural': 'VideosData',
                'ordering': ['keyword', '-published_at'],
            },
        ),
        migrations.AddIndex(
            model_name='videodata',
            index=models.Index(fields=['keyword', 'published_at'], name='youtube_mod_keyword_429002_idx'),
        ),
    ]
