# Generated by Django 3.0.7 on 2020-10-07 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoKeywordRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='videodata',
            options={'ordering': ['video_id', '-published_at'], 'verbose_name_plural': 'VideosData'},
        ),
        migrations.RemoveIndex(
            model_name='videodata',
            name='youtube_mod_keyword_429002_idx',
        ),
        migrations.RemoveField(
            model_name='videodata',
            name='keyword',
        ),
        migrations.AddIndex(
            model_name='videodata',
            index=models.Index(fields=['video_id', 'published_at'], name='youtube_mod_video_i_e998a9_idx'),
        ),
        migrations.AddField(
            model_name='videokeywordrelationship',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_videos', to='youtube_module.Keyword'),
        ),
        migrations.AddField(
            model_name='videokeywordrelationship',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_keywords', to='youtube_module.VideoData'),
        ),
    ]
