# Generated by Django 3.0.7 on 2020-10-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videokeywordrelationship',
            unique_together={('keyword', 'video')},
        ),
    ]
